### PR TITLE
meta: switch to vc14

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by xoviat** [comment]
@conda-forge-admin Please rerender

**Comment by xoviat** [comment]
@conda-forge-admin Please rerender

**Comment by jakirkham** [comment]
The `skip` needs to be updated as well.

**Comment by xoviat** [comment]
@jakirkham No it doesn't (you can build with vc14 and py27 at the same time). However, I would appreciate assistance with the batch file error.

**Comment by xoviat** [comment]
cc @conda-forge/ninja

**Comment by xoviat** [comment]
Also, @jakirkham could you merge?

**Pull request merged**
